steps:
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/myimage', '.']
  - name: 'docker'
    args: ['run', 'gcr.io/$PROJECT_ID/myimage', 'ls', '-R']
  - name: 'docker'
    args: ['run', 'gcr.io/$PROJECT_ID/myimage', 'python3', 'out/bin/binaryen-lit', 'test/lit/parse-error.wast']
  - name: 'docker'
    args: ['run', 'gcr.io/$PROJECT_ID/myimage', 'python3', 'check.py', '--binaryen-bin=out/bin']
options:
  machineType: 'E2_HIGHCPU_8'
